"""Start database

Revision ID: 5ce424aa35e5
Revises: 
Create Date: 2025-12-23 16:21:17.840762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce424aa35e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_genetic_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('milk_yield', sa.Float(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_genetic_tests')
    # ### end Alembic commands ###
